### ISSUE TITLE
Error when updating

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/Hook#53]
This is a somewhat recent issue, apparently occurring only with PDL/latin-lit

```
 mod_wsgi (pid=8605): Exception occurred processing WSGI script '/home/ubuntu/app/app.wsgi'.
 Traceback (most recent call last):
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/mongoengine-0.10.0-py3.4.egg/mongoengine/queryset/base.py", line 459, in updat
e
     upsert=upsert, **write_concern)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/pymongo-3.0.3-py3.4-linux-x86_64.egg/pymongo/collection.py", line 1958, in upd
ate
     check_keys, multi, manipulate, write_concern)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/pymongo-3.0.3-py3.4-linux-x86_64.egg/pymongo/collection.py", line 535, in _upd
ate
     _check_write_command_response(results)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/pymongo-3.0.3-py3.4-linux-x86_64.egg/pymongo/helpers.py", line 261, in _check_
write_command_response
     raise WriteError(error.get("errmsg"), error.get("code"), error)
 pymongo.errors.WriteError: new file allocation failure
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1836, in __call__
     return self.wsgi_app(environ, start_response)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1820, in wsgi_app
     response = self.make_response(self.handle_exception(e))
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1403, in handle_exception
     reraise(exc_type, exc_value, tb)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/_compat.py", line 33, in reraise
     raise value
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1817, in wsgi_app
     response = self.full_dispatch_request()
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1477, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1381, in handle_user_exception
     reraise(exc_type, exc_value, tb)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/_compat.py", line 33, in reraise
     raise value
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1475, in full_dispatch_request
     rv = self.dispatch_request()
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1461, in dispatch_request
     return self.view_functions[rule.endpoint](**req.view_args)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Hook-0.0.1-py3.4.egg/Hook/ext.py", line 276, in r_api_hooktest_endpoint
     return "", self.handle_hooktest_log(request), {}
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Hook-0.0.1-py3.4.egg/Hook/ext.py", line 813, in handle_hooktest_log
     test.update(**update)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/mongoengine-0.10.0-py3.4.egg/mongoengine/document.py", line 464, in update
     return self._qs.filter(**self._object_key).update_one(**kwargs)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/mongoengine-0.10.0-py3.4.egg/mongoengine/queryset/base.py", line 487, in updat
e_one
     upsert=upsert, multi=False, write_concern=write_concern, **update)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/mongoengine-0.10.0-py3.4.egg/mongoengine/queryset/base.py", line 470, in updat
e
     raise OperationError('Update failed (%s)' % str(err))
 mongoengine.errors.OperationError: Update failed (new file allocation failure)
 mod_wsgi (pid=8605): Exception occurred processing WSGI script '/home/ubuntu/app/app.wsgi'.
 Traceback (most recent call last):
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/mongoengine-0.10.0-py3.4.egg/mongoengine/queryset/base.py", line 459, in updat
e
     upsert=upsert, **write_concern)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/pymongo-3.0.3-py3.4-linux-x86_64.egg/pymongo/collection.py", line 1958, in upd
ate
     check_keys, multi, manipulate, write_concern)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/pymongo-3.0.3-py3.4-linux-x86_64.egg/pymongo/collection.py", line 535, in _upd
ate
     _check_write_command_response(results)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/pymongo-3.0.3-py3.4-linux-x86_64.egg/pymongo/helpers.py", line 261, in _check_
write_command_response
     raise WriteError(error.get("errmsg"), error.get("code"), error)
 pymongo.errors.WriteError: new file allocation failure
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1836, in __call__
     return self.wsgi_app(environ, start_response)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1820, in wsgi_app
     response = self.make_response(self.handle_exception(e))
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1403, in handle_exception
     reraise(exc_type, exc_value, tb)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/_compat.py", line 33, in reraise
     raise value
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1817, in wsgi_app
     response = self.full_dispatch_request()
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1477, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1381, in handle_user_exception
     reraise(exc_type, exc_value, tb)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/_compat.py", line 33, in reraise
     raise value
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1475, in full_dispatch_request
     rv = self.dispatch_request()
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1461, in dispatch_request
     return self.view_functions[rule.endpoint](**req.view_args)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Hook-0.0.1-py3.4.egg/Hook/ext.py", line 276, in r_api_hooktest_endpoint
     return "", self.handle_hooktest_log(request), {}
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Hook-0.0.1-py3.4.egg/Hook/ext.py", line 813, in handle_hooktest_log
     test.update(**update)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/mongoengine-0.10.0-py3.4.egg/mongoengine/document.py", line 464, in update
     return self._qs.filter(**self._object_key).update_one(**kwargs)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/mongoengine-0.10.0-py3.4.egg/mongoengine/queryset/base.py", line 487, in updat
e_one
     upsert=upsert, multi=False, write_concern=write_concern, **update)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/mongoengine-0.10.0-py3.4.egg/mongoengine/queryset/base.py", line 470, in updat
e
     raise OperationError('Update failed (%s)' % str(err))
 mongoengine.errors.OperationError: Update failed (new file allocation failure)
 mod_wsgi (pid=8606): Exception occurred processing WSGI script '/home/ubuntu/app/app.wsgi'.
 Traceback (most recent call last):
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/mongoengine-0.10.0-py3.4.egg/mongoengine/queryset/base.py", line 459, in updat
e
     upsert=upsert, **write_concern)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/pymongo-3.0.3-py3.4-linux-x86_64.egg/pymongo/collection.py", line 1958, in upd
ate
     check_keys, multi, manipulate, write_concern)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/pymongo-3.0.3-py3.4-linux-x86_64.egg/pymongo/collection.py", line 535, in _upd
ate
     _check_write_command_response(results)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/pymongo-3.0.3-py3.4-linux-x86_64.egg/pymongo/helpers.py", line 261, in _check_
write_command_response
     raise WriteError(error.get("errmsg"), error.get("code"), error)
 pymongo.errors.WriteError: new file allocation failure
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1836, in __call__
     return self.wsgi_app(environ, start_response)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1820, in wsgi_app
     response = self.make_response(self.handle_exception(e))
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1403, in handle_exception
     reraise(exc_type, exc_value, tb)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/_compat.py", line 33, in reraise
     raise value
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1817, in wsgi_app
     response = self.full_dispatch_request()
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1477, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1381, in handle_user_exception
     reraise(exc_type, exc_value, tb)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/_compat.py", line 33, in reraise
     raise value
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1475, in full_dispatch_request
     rv = self.dispatch_request()
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1461, in dispatch_request
     return self.view_functions[rule.endpoint](**req.view_args)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Hook-0.0.1-py3.4.egg/Hook/ext.py", line 276, in r_api_hooktest_endpoint
     return "", self.handle_hooktest_log(request), {}
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Hook-0.0.1-py3.4.egg/Hook/ext.py", line 813, in handle_hooktest_log
     test.update(**update)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/mongoengine-0.10.0-py3.4.egg/mongoengine/document.py", line 464, in update
     return self._qs.filter(**self._object_key).update_one(**kwargs)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/mongoengine-0.10.0-py3.4.egg/mongoengine/queryset/base.py", line 487, in updat
e_one
     upsert=upsert, multi=False, write_concern=write_concern, **update)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/mongoengine-0.10.0-py3.4.egg/mongoengine/queryset/base.py", line 470, in updat
e
     raise OperationError('Update failed (%s)' % str(err))
 mongoengine.errors.OperationError: Update failed (new file allocation failure)
 mod_wsgi (pid=8605): Exception occurred processing WSGI script '/home/ubuntu/app/app.wsgi'.
 Traceback (most recent call last):
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/mongoengine-0.10.0-py3.4.egg/mongoengine/queryset/base.py", line 459, in updat
e
     upsert=upsert, **write_concern)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/pymongo-3.0.3-py3.4-linux-x86_64.egg/pymongo/collection.py", line 1958, in upd
ate
     check_keys, multi, manipulate, write_concern)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/pymongo-3.0.3-py3.4-linux-x86_64.egg/pymongo/collection.py", line 535, in _upd
ate
     _check_write_command_response(results)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/pymongo-3.0.3-py3.4-linux-x86_64.egg/pymongo/helpers.py", line 261, in _check_
write_command_response
     raise WriteError(error.get("errmsg"), error.get("code"), error)
 pymongo.errors.WriteError: new file allocation failure
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1836, in __call__
     return self.wsgi_app(environ, start_response)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1820, in wsgi_app
     response = self.make_response(self.handle_exception(e))
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1403, in handle_exception
     reraise(exc_type, exc_value, tb)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/_compat.py", line 33, in reraise
     raise value
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1817, in wsgi_app
     response = self.full_dispatch_request()
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1477, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1381, in handle_user_exception
     reraise(exc_type, exc_value, tb)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/_compat.py", line 33, in reraise
     raise value
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1475, in full_dispatch_request
     rv = self.dispatch_request()
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg/flask/app.py", line 1461, in dispatch_request
     return self.view_functions[rule.endpoint](**req.view_args)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Hook-0.0.1-py3.4.egg/Hook/ext.py", line 276, in r_api_hooktest_endpoint
     return "", self.handle_hooktest_log(request), {}
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/Hook-0.0.1-py3.4.egg/Hook/ext.py", line 813, in handle_hooktest_log
     test.update(**update)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/mongoengine-0.10.0-py3.4.egg/mongoengine/document.py", line 464, in update
     return self._qs.filter(**self._object_key).update_one(**kwargs)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/mongoengine-0.10.0-py3.4.egg/mongoengine/queryset/base.py", line 487, in updat
e_one
     upsert=upsert, multi=False, write_concern=write_concern, **update)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/mongoengine-0.10.0-py3.4.egg/mongoengine/queryset/base.py", line 470, in updat
e
     raise OperationError('Update failed (%s)' % str(err))
 mongoengine.errors.OperationError: Update failed (new file allocation failure)
 mod_wsgi (pid=8606): Exception occurred processing WSGI script '/home/ubuntu/app/app.wsgi'.
 Traceback (most recent call last):
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/mongoengine-0.10.0-py3.4.egg/mongoengine/queryset/base.py", line 459, in updat
e
     upsert=upsert, **write_concern)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/pymongo-3.0.3-py3.4-linux-x86_64.egg/pymongo/collection.py", line 1958, in upd
ate
     check_keys, multi, manipulate, write_concern)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/pymongo-3.0.3-py3.4-linux-x86_64.egg/pymongo/collection.py", line 535, in _upd
ate
     _check_write_command_response(results)
   File "/home/ubuntu/app/env/lib/python3.4/site-packages/pymongo-3.0.3-py3.4-linux-x86_64.egg/pymongo/helpers.py", line 261, in _check_
write_command_response
     raise WriteError(error.get("errmsg"), error.get("code"), error)
 pymongo.errors.WriteError: new file allocation failure
```

**Comment by PonteIneptique** [comment]
Quite possibly related to this http://serverfault.com/questions/657896/mongodb-insert-operation-fails-but-disk-is-free
 @balmas it is possible we need more space (we only have 8 gb on `/` should we double that up ?. Logs are taking a already 1gg...)

```
drwxr-xr-x  4 mongodb mongodb 4.0K Nov 16 08:40 .
-rw-------  1 mongodb nogroup  64M Aug 17 18:12 Hook5.0
-rw-------  1 mongodb nogroup 256M Aug 17 18:25 Hook5.1
-rw-------  1 mongodb nogroup  16M Aug 17 18:12 Hook5.ns
-rw-------  1 mongodb nogroup  64M Dec  1 19:12 Hook_DB.0
-rw-------  1 mongodb nogroup 256M Dec  1 19:15 Hook_DB.1
-rw-------  1 mongodb nogroup 256M Dec  1 19:15 Hook_DB.2
-rw-------  1 mongodb nogroup 512M Dec  1 19:15 Hook_DB.3
-rw-------  1 mongodb nogroup  16M Dec  1 19:12 Hook_DB.ns
```

**Comment by PonteIneptique** [comment]
Pinging @sonofmun so he is aware of it.

**Comment by PonteIneptique** [comment]
Confirmation -> `Cannot repair database Hook_DB having size: 1157627904 (bytes) because free disk space is: 903458816 (bytes)`

**Comment by sonofmun** [comment]
If Homer is keeping all the logs for all of the tests, then I think you will need to increase the storage space.  Are you using Redis or Mongo as your celery task db?  You might want to try deleting the DB there, since that might also be choked with tasks that have already been completed.  You could also try clearing the Redis queue (if you are using Redis).  @mittagessen (Ben) might know something more about this.

**Comment by PonteIneptique** [comment]
Nothing is stored on Redis or Homer, except the fail/success status :)
This is an AWS space issue.

**Comment by balmas** [comment]
New 20GB volume added, mounted at /mnt/data
